### ISSUE TITLE
master build failure on Windows (tests)

### ISSUE THREAD

**Issue by macTh3Knif3** [theia-ide/yang-lsp#152]
built using cygwin (gradelw) and powershell (gradlew.bat) also in eclipse

![image](https://user-images.githubusercontent.com/1890444/48422574-ddd92780-e756-11e8-8828-a673cabec985.png)

Also the link to builds is empty (returns a 404)
https://hub.docker.com/r/typefox/yang-lsp/builds

$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)

:io.typefox.yang.ide:testClasses
:io.typefox.yang.ide:test

io.typefox.yang.tests.editor.syntaxcoloring.YangSemanticHighlightingCalculatorTest > checkDescription_multiLine FAILED
    org.junit.ComparisonFailure at YangSemanticHighlightingCalculatorTest.java:210

org.junit.ComparisonFailure: expected:<... : []
1 : []
2 : [3:[1:[keyword.other.unit, source.yang]]
3 : [0:11:[keyword.other.unit, source.yang]]
4 : [0:2]:[keyword.other.unit...> but was:<... : []
1 : []
2 : [3:[2:[keyword.other.unit, source.yang]]
3 : [0:12:[keyword.other.unit, source.yang]]
4 : [0:3]:[keyword.other.unit...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.xtext.testing.AbstractLanguageServerTest.assertEquals(AbstractLanguageServerTest.java:1305)
	at io.typefox.yang.tests.editor.syntaxcoloring.YangSemanticHighlightingCalculatorTest.assertInfos(YangSemanticHighlightingCalculatorTest.java:210)

**Comment by carldou** [comment]
same problem, in win10 and java 1.8.0_201.
by using -x test as postfix for build command, build is successful, but still cannot work in VS code with Yang plugin.

**Comment by JanKoehnlein** [comment]
@carldou why do you want to recompile instead of just consuming the VS Code extension from the VS Code marketplace?

**Comment by carldou** [comment]
> @carldou why do you want to recompile instead of just consuming the VS Code extension from the VS Code marketplace?

I install the Yang VS Code Extension from VS Code marketplace, but it only highlights the grammer without automatic code completion. So I thought maybe I need to install this yang-lsp additionally. Now, it seems not necessary.

**Comment by JanKoehnlein** [comment]
I just tried on Windows 10 with latest VSCode and I do get code completion

<img width="515" alt="screen shot 2019-02-13 at 09 18 38" src="https://user-images.githubusercontent.com/377752/52696921-8a9e8d00-2f70-11e9-9b3d-d02b0a17958e.png">

Did you install the correct extension? There is another one with syntax highlighting only.

It may also be a problem with (locating) Java on your machine. Do you get messages from VSCode that the language server couldn't be started or keeps crashing?

**Comment by carldou** [comment]
> I just tried on Windows 10 with latest VSCode and I do get code completion
> 
> <img alt="screen shot 2019-02-13 at 09 18 38" width="515" src="https://user-images.githubusercontent.com/377752/52696921-8a9e8d00-2f70-11e9-9b3d-d02b0a17958e.png">
> 
> Did you install the correct extension? There is another one with syntax highlighting only.
> 
> It may also be a problem with (locating) Java on your machine. Do you get messages from VSCode that the language server couldn't be started or keeps crashing?

I also use Windows 10 with VS code version 1.31.1.

![image](https://user-images.githubusercontent.com/41419292/52697883-58f7e700-2fad-11e9-9235-bd7e013b10f2.png)

There is one error from VS Code, as shown here.

![image](https://user-images.githubusercontent.com/41419292/52698068-b68c3380-2fad-11e9-9c4e-622db2171f84.png)

**Comment by riddler63** [comment]
Hello,

I have exactly the same issue with VSCode and building yang-lsp and I noticed that it started to apear after I install GIT with VSCode as default text editor. Before that Yang VS Code Extension was working fine.

**Comment by JanKoehnlein** [comment]
Which version of Java is installed on your system?

**Comment by riddler63** [comment]
> Which version of Java is installed on your system?
This one:
`java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)`
