### ISSUE TITLE
LSP return `Internal error.`

### ISSUE THREAD

**Issue by Ian0113** [theia-ide/yang-lsp#219]
When I open the vscode and attach into the docker container.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/73458586/169335384-95298b6f-5cbc-450a-a09d-1f9f926eb3d9.png">

 - Step to reproduce
     1. open vscode
     2. attach to the docker container
        <img width="520" alt="image" src="https://user-images.githubusercontent.com/73458586/169336699-35b56ff8-45fc-4580-8895-b68d32b9cd07.png">
     3. install JRE
        <img width="490" alt="image" src="https://user-images.githubusercontent.com/73458586/169336043-72031972-67a5-45ed-903b-74b938819e1c.png">

     4. install LSP in the container
       <img width="518" alt="image" src="https://user-images.githubusercontent.com/73458586/169336965-56eccf18-2d01-4a81-a1f2-70ac3b64ab1f.png">

<details>
<summary>Error log</summary>

```
root@a79a363c4066:/# cat /root/.vscode-server/data/logs/20220519T143922/exthost12/output_logging_20220519T154224/2-Yan
g\ Language\ Server.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/root/.vscode-server/extensions/typefox.yang-vscode-2.1.0/server/lib/guice-3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Error - 3:42:28 PM] Error during request: : org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /root/yuma123/netconf/test/netconfd/ietf-netmod-sub-intf-vlan-model/ietf-interfaces-ethernet-like@2017-07-03.yang (No such file or directory)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:266)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:67)
	at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:55)
	at org.eclipse.xtext.build.Indexer.getDeltasForChangedResources(Indexer.java:241)
	at org.eclipse.xtext.build.Indexer.computeAndIndexAffected(Indexer.java:191)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:245)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:404)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:386)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:106)
	at org.eclipse.xtext.ide.server.ProjectManager.doInitialBuild(ProjectManager.java:97)
	at org.eclipse.xtext.ide.server.BuildManager.doInitialBuild(BuildManager.java:164)
	at org.eclipse.xtext.ide.server.WorkspaceManager.refreshWorkspaceConfig(WorkspaceManager.java:233)
	at org.eclipse.xtext.ide.server.WorkspaceManager.initialize(WorkspaceManager.java:170)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$initialize$0(LanguageServerImpl.java:224)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: /root/yuma123/netconf/test/netconfd/ietf-netmod-sub-intf-vlan-model/ietf-interfaces-ethernet-like@2017-07-03.yang (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.eclipse.emf.ecore.resource.impl.FileURIHandlerImpl.createInputStream(FileURIHandlerImpl.java:99)
	at org.eclipse.xtext.resource.ExternalContentSupport$ExternalContentAwareURIHandler.createInputStream(ExternalContentSupport.java:75)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:299)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 20 more
May 19, 2022 3:42:28 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /root/yuma123/netconf/test/netconfd/ietf-netmod-sub-intf-vlan-model/ietf-interfaces-ethernet-like@2017-07-03.yang (No such file or directory)
java.util.concurrent.CompletionException: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /root/yuma123/netconf/test/netconfd/ietf-netmod-sub-intf-vlan-model/ietf-interfaces-ethernet-like@2017-07-03.yang (No such file or directory)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.logAndCompleteExceptionally(AbstractRequest.java:73)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /root/yuma123/netconf/test/netconfd/ietf-netmod-sub-intf-vlan-model/ietf-interfaces-ethernet-like@2017-07-03.yang (No such file or directory)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:266)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:67)
	at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:55)
	at org.eclipse.xtext.build.Indexer.getDeltasForChangedResources(Indexer.java:241)
	at org.eclipse.xtext.build.Indexer.computeAndIndexAffected(Indexer.java:191)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:245)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:404)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:386)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:106)
	at org.eclipse.xtext.ide.server.ProjectManager.doInitialBuild(ProjectManager.java:97)
	at org.eclipse.xtext.ide.server.BuildManager.doInitialBuild(BuildManager.java:164)
	at org.eclipse.xtext.ide.server.WorkspaceManager.refreshWorkspaceConfig(WorkspaceManager.java:233)
	at org.eclipse.xtext.ide.server.WorkspaceManager.initialize(WorkspaceManager.java:170)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$initialize$0(LanguageServerImpl.java:224)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:50)
	... 5 more
Caused by: java.io.FileNotFoundException: /root/yuma123/netconf/test/netconfd/ietf-netmod-sub-intf-vlan-model/ietf-interfaces-ethernet-like@2017-07-03.yang (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.eclipse.emf.ecore.resource.impl.FileURIHandlerImpl.createInputStream(FileURIHandlerImpl.java:99)
	at org.eclipse.xtext.resource.ExternalContentSupport$ExternalContentAwareURIHandler.createInputStream(ExternalContentSupport.java:75)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:299)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 20 more

[Error - 3:42:28 PM] Server initialization failed.
  Message: Internal error.
  Code: -32603
java.util.concurrent.CompletionException: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /root/yuma123/netconf/test/netconfd/ietf-netmod-sub-intf-vlan-model/ietf-interfaces-ethernet-like@2017-07-03.yang (No such file or directory)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.logAndCompleteExceptionally(AbstractRequest.java:73)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: /root/yuma123/netconf/test/netconfd/ietf-netmod-sub-intf-vlan-model/ietf-interfaces-ethernet-like@2017-07-03.yang (No such file or directory)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:266)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:67)
	at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:55)
	at org.eclipse.xtext.build.Indexer.getDeltasForChangedResources(Indexer.java:241)
	at org.eclipse.xtext.build.Indexer.computeAndIndexAffected(Indexer.java:191)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:245)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:404)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:386)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:106)
	at org.eclipse.xtext.ide.server.ProjectManager.doInitialBuild(ProjectManager.java:97)
	at org.eclipse.xtext.ide.server.BuildManager.doInitialBuild(BuildManager.java:164)
	at org.eclipse.xtext.ide.server.WorkspaceManager.refreshWorkspaceConfig(WorkspaceManager.java:233)
	at org.eclipse.xtext.ide.server.WorkspaceManager.initialize(WorkspaceManager.java:170)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$initialize$0(LanguageServerImpl.java:224)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:50)
	... 5 more
Caused by: java.io.FileNotFoundException: /root/yuma123/netconf/test/netconfd/ietf-netmod-sub-intf-vlan-model/ietf-interfaces-ethernet-like@2017-07-03.yang (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.eclipse.emf.ecore.resource.impl.FileURIHandlerImpl.createInputStream(FileURIHandlerImpl.java:99)
	at org.eclipse.xtext.resource.ExternalContentSupport$ExternalContentAwareURIHandler.createInputStream(ExternalContentSupport.java:75)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:299)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 20 more
```
</details>

**Comment by Ian0113** [comment]
I solve the files not found in my project, but the vscode still returns `internal error`

- debug log
```
root@fc8fc6594751:~/.vscode-server# cat ./data/logs/20220520T061938/exthost9/output_logging_20220520T080137/2-Yang\ Language\ Server.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/root/.vscode-server/extensions/typefox.yang-vscode-2.1.0/server/lib/guice-3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Error - 8:01:55 AM] Error during request: : java.lang.StackOverflowError
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:496)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
May 20, 2022 8:01:55 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.StackOverflowError
java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.logAndCompleteExceptionally(AbstractRequest.java:73)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.StackOverflowError
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:496)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
[Error - 8:01:55 AM] Server initialization failed.
  Message: Internal error.
  Code: -32603
java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.eclipse.xtext.ide.server.concurrent.AbstractRequest.logAndCompleteExceptionally(AbstractRequest.java:73)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.StackOverflowError
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:496)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)
	at io.typefox.yang.scoping.ScopeContextProvider.inlineGrouping(ScopeContextProvider.java:1240)
	at io.typefox.yang.scoping.ScopeContextProvider._inlineGrouping(ScopeContextProvider.java:508)

```

**Comment by Ian0113** [comment]
Hi, @dhuebner 

I solved the `StackOverflowError` a few days ago, the problem is a broken symbolic link influences the language server, so I clean the broken symbolic link to solve the `StackOverflowError`.

**To reproduce**
Sorry, I can't reproduce the problem, because the docker container has been removed and I don't know how to make a broken symbolic link.

If there is a way to make a broken symbolic link, please tell me, and I will reproduce the problem, thanks.

Thanks,
Ian

**Comment by dhuebner** [comment]
@Ian0113 
Thanks for your feedback.
Should we close this issue then?

**Comment by Ian0113** [comment]
Hi, @dhuebner 

We can close this issue until it happened again.

Thanks,
Ian
